# Generated by Django 2.1.7 on 2019-03-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': '菜系', 'verbose_name_plural': '菜系'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': '菜品', 'verbose_name_plural': '菜品列表'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': '餐厅', 'verbose_name_plural': '餐厅列表'},
        ),
    ]
